//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class StationeryEntities : DbContext
{
    public StationeryEntities()
        : base("name=StationeryEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Category> Categories { get; set; }
    public virtual DbSet<CollectionPoint> CollectionPoints { get; set; }
    public virtual DbSet<Department> Departments { get; set; }
    public virtual DbSet<Disbursement> Disbursements { get; set; }
    public virtual DbSet<Disbursement_Item> Disbursement_Item { get; set; }
    public virtual DbSet<Discrepency> Discrepencies { get; set; }
    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<Item> Items { get; set; }
    public virtual DbSet<Item_PurchaseOrder> Item_PurchaseOrder { get; set; }
    public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
    public virtual DbSet<Requisition> Requisitions { get; set; }
    public virtual DbSet<Requisition_Item> Requisition_Item { get; set; }
    public virtual DbSet<Retrieval> Retrievals { get; set; }
    public virtual DbSet<StockCard> StockCards { get; set; }
    public virtual DbSet<Supplier> Suppliers { get; set; }
    public virtual DbSet<PriceList> PriceLists { get; set; }
}
