//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Items = new HashSet<Item>();
    }

    public int CategoryID { get; set; }
    public string CategoryName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Item> Items { get; set; }
}

public partial class CollectionPoint
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CollectionPoint()
    {
        this.Departments = new HashSet<Department>();
    }

    public int CollectionLocationID { get; set; }
    public string CollectionPoint1 { get; set; }
    public string DefaultCollectionTime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Department> Departments { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.Disbursements = new HashSet<Disbursement>();
        this.Employees = new HashSet<Employee>();
        this.Requisitions = new HashSet<Requisition>();
    }

    public string DeptCode { get; set; }
    public Nullable<int> CollectionLocationID { get; set; }
    public string DeptName { get; set; }
    public string DeptContactName { get; set; }
    public string DeptTelephone { get; set; }
    public string DeptFax { get; set; }

    public virtual CollectionPoint CollectionPoint { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Disbursement> Disbursements { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Employee> Employees { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisition> Requisitions { get; set; }
}

public partial class Disbursement
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Disbursement()
    {
        this.Disbursement_Item = new HashSet<Disbursement_Item>();
        this.Requisitions = new HashSet<Requisition>();
    }

    public int DisbursementID { get; set; }
    public Nullable<int> RetrievalID { get; set; }
    public string DeptCode { get; set; }
    public string CollectionTime { get; set; }
    public Nullable<System.DateTime> CollectionDate { get; set; }
    public string Status { get; set; }
    public string AccessCode { get; set; }

    public virtual Department Department { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Disbursement_Item> Disbursement_Item { get; set; }
    public virtual Retrieval Retrieval { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisition> Requisitions { get; set; }
}

public partial class Disbursement_Item
{
    public int DisbursementID { get; set; }
    public string ItemCode { get; set; }
    public Nullable<int> ActualQty { get; set; }
    public string Remarks { get; set; }
    public Nullable<int> TotalRequestedQty { get; set; }

    public virtual Disbursement Disbursement { get; set; }
    public virtual Item Item { get; set; }
}

public partial class Discrepency
{
    public int DiscrepencyID { get; set; }
    public string ItemCode { get; set; }
    public Nullable<int> ApprovedBy { get; set; }
    public Nullable<int> RequestedBy { get; set; }
    public Nullable<int> AdjustmentQty { get; set; }
    public string Remarks { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Status { get; set; }
    public Nullable<decimal> TotalDiscrepencyAmount { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Item Item { get; set; }
    public virtual Employee Employee1 { get; set; }
}

public partial class Employee
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {
        this.Discrepencies = new HashSet<Discrepency>();
        this.Discrepencies1 = new HashSet<Discrepency>();
        this.PurchaseOrders = new HashSet<PurchaseOrder>();
        this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
        this.Requisitions = new HashSet<Requisition>();
        this.Requisitions1 = new HashSet<Requisition>();
        this.Retrievals = new HashSet<Retrieval>();
    }

    public int EmpID { get; set; }
    public string DeptCode { get; set; }
    public string EmpName { get; set; }
    public string Role { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string IsTempHead { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }

    public virtual Department Department { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Discrepency> Discrepencies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Discrepency> Discrepencies1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisition> Requisitions { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisition> Requisitions1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Retrieval> Retrievals { get; set; }
}

public partial class Item
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {
        this.Disbursement_Item = new HashSet<Disbursement_Item>();
        this.Discrepencies = new HashSet<Discrepency>();
        this.Item_PurchaseOrder = new HashSet<Item_PurchaseOrder>();
        this.Requisition_Item = new HashSet<Requisition_Item>();
        this.StockCards = new HashSet<StockCard>();
        this.PriceLists = new HashSet<PriceList>();
    }

    public string ItemCode { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string Description { get; set; }
    public int ReorderLevel { get; set; }
    public int ReorderQty { get; set; }
    public string UnitOfMeasure { get; set; }
    public string Bin { get; set; }
    public string ActiveStatus { get; set; }
    public Nullable<int> BalanceQty { get; set; }

    public virtual Category Category { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Disbursement_Item> Disbursement_Item { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Discrepency> Discrepencies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Item_PurchaseOrder> Item_PurchaseOrder { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisition_Item> Requisition_Item { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StockCard> StockCards { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PriceList> PriceLists { get; set; }
}

public partial class Item_PurchaseOrder
{
    public int PurchaseOrderID { get; set; }
    public string ItemCode { get; set; }
    public Nullable<int> OrderQty { get; set; }
    public Nullable<decimal> Amount { get; set; }

    public virtual Item Item { get; set; }
    public virtual PurchaseOrder PurchaseOrder { get; set; }
}

public partial class PriceList
{
    public string SupplierCode { get; set; }
    public string ItemCode { get; set; }
    public Nullable<decimal> Price { get; set; }
    public Nullable<int> SupplierRank { get; set; }
    public string TenderYear { get; set; }

    public virtual Item Item { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class PurchaseOrder
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PurchaseOrder()
    {
        this.Item_PurchaseOrder = new HashSet<Item_PurchaseOrder>();
    }

    public int PurchaseOrderID { get; set; }
    public Nullable<int> RequestedBy { get; set; }
    public string SupplierCode { get; set; }
    public Nullable<int> ApprovedBy { get; set; }
    public Nullable<decimal> TotalAmount { get; set; }
    public string Status { get; set; }
    public string Remarks { get; set; }
    public string DONumber { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public Nullable<System.DateTime> ExpectedDate { get; set; }
    public Nullable<System.DateTime> ApprovedByDate { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Item_PurchaseOrder> Item_PurchaseOrder { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class Requisition
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Requisition()
    {
        this.Requisition_Item = new HashSet<Requisition_Item>();
    }

    public int RequisitionID { get; set; }
    public Nullable<int> DisbursementID { get; set; }
    public Nullable<int> RequestedBy { get; set; }
    public Nullable<int> ApprovedBy { get; set; }
    public Nullable<System.DateTime> RequestDate { get; set; }
    public string Status { get; set; }
    public string Remarks { get; set; }
    public string DeptCode { get; set; }

    public virtual Disbursement Disbursement { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisition_Item> Requisition_Item { get; set; }
    public virtual Department Department { get; set; }
}

public partial class Requisition_Item
{
    public int RequisitionID { get; set; }
    public string ItemCode { get; set; }
    public Nullable<int> RequestedQty { get; set; }

    public virtual Item Item { get; set; }
    public virtual Requisition Requisition { get; set; }
}

public partial class Retrieval
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Retrieval()
    {
        this.Disbursements = new HashSet<Disbursement>();
    }

    public int RetrievalID { get; set; }
    public Nullable<int> RetrievedBy { get; set; }
    public Nullable<System.DateTime> RetrievedDate { get; set; }
    public string RetrievalStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Disbursement> Disbursements { get; set; }
    public virtual Employee Employee { get; set; }
}

public partial class StockCard
{
    public int TransactionID { get; set; }
    public string ItemCode { get; set; }
    public string TransactionType { get; set; }
    public Nullable<int> Qty { get; set; }
    public Nullable<int> Balance { get; set; }
    public Nullable<int> TransactionDetailID { get; set; }

    public virtual Item Item { get; set; }
}

public partial class Supplier
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {
        this.PurchaseOrders = new HashSet<PurchaseOrder>();
        this.PriceLists = new HashSet<PriceList>();
    }

    public string SupplierCode { get; set; }
    public string SupplierName { get; set; }
    public string SupplierContactName { get; set; }
    public string SupplierPhone { get; set; }
    public string SupplierFax { get; set; }
    public string SupplierAddress { get; set; }
    public string SupplierEmail { get; set; }
    public string ActiveStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PriceList> PriceLists { get; set; }
}
